// <auto-generated />
using System;
using DigiRega.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DigiRega.Server.Migrations
{
    [DbContext(typeof(DigiRegaDbContext))]
    [Migration("20210117122728_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("DigiRega.Server.Model.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("DigiRega.Server.Model.EmailMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("EmailMessages");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Entry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ManagerComment")
                        .HasColumnType("text");

                    b.Property<string>("OcComment")
                        .HasColumnType("text");

                    b.Property<int>("RaceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SentById")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("RaceId");

                    b.HasIndex("SentById");

                    b.ToTable("Entries");

                    b.HasDiscriminator<string>("EntryType").HasValue("Entry");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Race", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("LongName")
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("DigiRega.Server.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("Type").HasValue("User");
                });

            modelBuilder.Entity("DigiRega.Server.Model.CrewChange", b =>
                {
                    b.HasBaseType("DigiRega.Server.Model.Entry");

                    b.Property<int>("BowNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("BowNumber");

                    b.HasDiscriminator().HasValue("CrewChange");
                });

            modelBuilder.Entity("DigiRega.Server.Model.LateEntry", b =>
                {
                    b.HasBaseType("DigiRega.Server.Model.Entry");

                    b.HasDiscriminator().HasValue("LateEntry");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Withdrawal", b =>
                {
                    b.HasBaseType("DigiRega.Server.Model.Entry");

                    b.Property<int>("BowNumber")
                        .ValueGeneratedOnUpdateSometimes()
                        .HasColumnType("integer")
                        .HasColumnName("BowNumber");

                    b.HasDiscriminator().HasValue("Withdrawal");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Manager", b =>
                {
                    b.HasBaseType("DigiRega.Server.Model.User");

                    b.Property<int>("ClubId")
                        .HasColumnType("integer");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasIndex("ClubId");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("DigiRega.Server.Model.StaffMember", b =>
                {
                    b.HasBaseType("DigiRega.Server.Model.User");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasDiscriminator().HasValue("StaffMember");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PasswordHash = new byte[] { 36, 241, 97, 207, 65, 14, 211, 94, 86, 121, 247, 30, 211, 119, 161, 61, 249, 52, 145, 193, 120, 186, 103, 37, 159, 145, 151, 218, 110, 24, 198, 203, 127, 68, 28, 247, 180, 84, 133, 249, 20, 20, 176, 230, 122, 31, 247, 61, 57, 45, 157, 94, 138, 63, 141, 185, 252, 4, 255, 173, 126, 20, 109, 76 },
                            PasswordSalt = new byte[] { 146, 130, 208, 136, 10, 72, 214, 3, 77, 164, 199, 253, 63, 183, 17, 213, 211, 253, 12, 205, 104, 121, 208, 136, 174, 252, 172, 70, 59, 165, 212, 3, 18, 159, 218, 35, 22, 253, 100, 82, 70, 48, 109, 105, 135, 11, 60, 126, 81, 217, 135, 129, 231, 153, 182, 17, 115, 239, 164, 208, 50, 24, 192, 253, 89, 246, 118, 199, 20, 54, 235, 27, 160, 40, 60, 115, 255, 1, 118, 181, 205, 232, 153, 186, 187, 144, 50, 187, 77, 162, 133, 6, 20, 17, 148, 135, 187, 144, 190, 53, 63, 67, 215, 148, 50, 108, 58, 179, 174, 88, 222, 106, 142, 11, 228, 253, 7, 186, 70, 129, 251, 78, 58, 11, 245, 119, 192, 152 },
                            Username = "admin",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("DigiRega.Server.Model.EmailMessage", b =>
                {
                    b.OwnsOne("DigiRega.Server.Model.EmailRecipient", "Recipient", b1 =>
                        {
                            b1.Property<int>("EmailMessageId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("EmailMessageId");

                            b1.ToTable("EmailMessages");

                            b1.WithOwner()
                                .HasForeignKey("EmailMessageId");
                        });

                    b.Navigation("Recipient")
                        .IsRequired();
                });

            modelBuilder.Entity("DigiRega.Server.Model.Entry", b =>
                {
                    b.HasOne("DigiRega.Server.Model.Club", "Club")
                        .WithMany()
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiRega.Server.Model.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DigiRega.Server.Model.Manager", "SentBy")
                        .WithMany()
                        .HasForeignKey("SentById");

                    b.Navigation("Club");

                    b.Navigation("Race");

                    b.Navigation("SentBy");
                });

            modelBuilder.Entity("DigiRega.Server.Model.User", b =>
                {
                    b.OwnsMany("DigiRega.Server.Model.RefreshToken", "RefreshTokens", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<DateTime>("ExpiresAt")
                                .HasColumnType("timestamp without time zone");

                            b1.Property<string>("Token")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("UserId", "Id");

                            b1.ToTable("Users_RefreshTokens");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("DigiRega.Server.Model.CrewChange", b =>
                {
                    b.OwnsMany("DigiRega.Server.Model.Substitution", "Substitutions", b1 =>
                        {
                            b1.Property<int>("CrewChangeId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.HasKey("CrewChangeId", "Id");

                            b1.ToTable("Substitution");

                            b1.WithOwner()
                                .HasForeignKey("CrewChangeId");

                            b1.OwnsOne("DigiRega.Server.Model.Athlete", "New", b2 =>
                                {
                                    b2.Property<int>("SubstitutionCrewChangeId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SubstitutionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .UseIdentityByDefaultColumn();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("YearOfBirth")
                                        .HasColumnType("integer");

                                    b2.HasKey("SubstitutionCrewChangeId", "SubstitutionId");

                                    b2.ToTable("Substitution");

                                    b2.WithOwner()
                                        .HasForeignKey("SubstitutionCrewChangeId", "SubstitutionId");
                                });

                            b1.OwnsOne("DigiRega.Server.Model.Athlete", "Old", b2 =>
                                {
                                    b2.Property<int>("SubstitutionCrewChangeId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SubstitutionId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .UseIdentityByDefaultColumn();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("YearOfBirth")
                                        .HasColumnType("integer");

                                    b2.HasKey("SubstitutionCrewChangeId", "SubstitutionId");

                                    b2.ToTable("Substitution");

                                    b2.WithOwner()
                                        .HasForeignKey("SubstitutionCrewChangeId", "SubstitutionId");
                                });

                            b1.Navigation("New")
                                .IsRequired();

                            b1.Navigation("Old")
                                .IsRequired();
                        });

                    b.Navigation("Substitutions");
                });

            modelBuilder.Entity("DigiRega.Server.Model.LateEntry", b =>
                {
                    b.OwnsMany("DigiRega.Server.Model.CrewMember", "Crew", b1 =>
                        {
                            b1.Property<int>("LateEntryId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .UseIdentityByDefaultColumn();

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.HasKey("LateEntryId", "Id");

                            b1.ToTable("CrewMember");

                            b1.WithOwner()
                                .HasForeignKey("LateEntryId");

                            b1.OwnsOne("DigiRega.Server.Model.Athlete", "Athlete", b2 =>
                                {
                                    b2.Property<int>("CrewMemberLateEntryId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("CrewMemberId")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .UseIdentityByDefaultColumn();

                                    b2.Property<string>("FirstName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<string>("LastName")
                                        .IsRequired()
                                        .HasColumnType("text");

                                    b2.Property<int>("YearOfBirth")
                                        .HasColumnType("integer");

                                    b2.HasKey("CrewMemberLateEntryId", "CrewMemberId");

                                    b2.ToTable("CrewMember");

                                    b2.WithOwner()
                                        .HasForeignKey("CrewMemberLateEntryId", "CrewMemberId");
                                });

                            b1.Navigation("Athlete")
                                .IsRequired();
                        });

                    b.Navigation("Crew");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Manager", b =>
                {
                    b.HasOne("DigiRega.Server.Model.Club", "Club")
                        .WithMany("Managers")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Club");
                });

            modelBuilder.Entity("DigiRega.Server.Model.Club", b =>
                {
                    b.Navigation("Managers");
                });
#pragma warning restore 612, 618
        }
    }
}
